### ISSUE TITLE
GitHub Actions stack trace parser test

### ISSUE THREAD

**Issue by andrewda** [andrewda/dynamoose#1]
Test issue

**Comment by andrewda** [comment]
comment

**Comment by andrewda** [comment]
comment 2

**Comment by andrewda** [comment]
comment 3

**Comment by andrewda** [comment]
comment 4

**Comment by andrewda** [comment]
comment 5

**Comment by andrewda** [comment]
comment 6

**Comment by andrewda** [comment]
@dynamoose/bot stacktrace-parser
Commit Hash: 8d8d5fe6dedeb8480fa02f422469754a8895f666

/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17
        throw new Error_1.default.InvalidParameter("You must pass in a Model or model name as a string.");
        ^

InvalidParameter: You must pass in a Model or model name as a string.
    at returnObject (/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17:15)
    at Object.<anonymous> (/home/andrewda/Development/dynamoose/playground.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by andrewda** [comment]
@dynamoose/bot stacktrace-parser
Commit Hash: 8d8d5fe6dedeb8480fa02f422469754a8895f666

```
/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17
        throw new Error_1.default.InvalidParameter("You must pass in a Model or model name as a string.");
        ^

InvalidParameter: You must pass in a Model or model name as a string.
    at returnObject (/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17:15)
    at Object.<anonymous> (/home/andrewda/Development/dynamoose/playground.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by andrewda** [comment]
@dynamoose/bot stacktrace-parser
Commit Hash: 8d8d5fe6dedeb8480fa02f422469754a8895f666

```
/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17
        throw new Error_1.default.InvalidParameter("You must pass in a Model or model name as a string.");
        ^

InvalidParameter: You must pass in a Model or model name as a string.
    at returnObject (/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17:15)
    at Object.<anonymous> (/home/andrewda/Development/dynamoose/playground.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by andrewda** [comment]
@dynamoose/bot stacktrace-parser
Commit Hash: 8d8d5fe6dedeb8480fa02f422469754a8895f666

```
/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17
        throw new Error_1.default.InvalidParameter("You must pass in a Model or model name as a string.");
        ^

InvalidParameter: You must pass in a Model or model name as a string.
    at returnObject (/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17:15)
    at Object.<anonymous> (/home/andrewda/Development/dynamoose/playground.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by andrewda** [comment]
@dynamoose/bot stacktrace-parser
Commit Hash: 8d8d5fe6dedeb8480fa02f422469754a8895f666

```
/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17
        throw new Error_1.default.InvalidParameter("You must pass in a Model or model name as a string.");
        ^

InvalidParameter: You must pass in a Model or model name as a string.
    at returnObject (/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17:15)
    at Object.<anonymous> (/home/andrewda/Development/dynamoose/playground.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by andrewda** [comment]
@dynamoose/bot stacktrace-parser
Commit Hash: 8d8d5fe6dedeb8480fa02f422469754a8895f666

```
/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17
        throw new Error_1.default.InvalidParameter("You must pass in a Model or model name as a string.");
        ^

InvalidParameter: You must pass in a Model or model name as a string.
    at returnObject (/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17:15)
    at Object.<anonymous> (/home/andrewda/Development/dynamoose/playground.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by andrewda** [comment]
@dynamoose/bot stacktrace-parser
Commit Hash: 8d8d5fe6dedeb8480fa02f422469754a8895f666

```
/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17
        throw new Error_1.default.InvalidParameter("You must pass in a Model or model name as a string.");
        ^

InvalidParameter: You must pass in a Model or model name as a string.
    at returnObject (/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17:15)
    at Object.<anonymous> (/home/andrewda/Development/dynamoose/playground.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by andrewda** [comment]
@dynamoose/bot stacktrace-parser
Commit Hash: 8d8d5fe6dedeb8480fa02f422469754a8895f666

```
/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17
        throw new Error_1.default.InvalidParameter("You must pass in a Model or model name as a string.");
        ^

InvalidParameter: You must pass in a Model or model name as a string.
    at returnObject (/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17:15)
    at Object.<anonymous> (/home/andrewda/Development/dynamoose/playground.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by andrewda** [comment]
@dynamoose/bot stacktrace-parser
Commit Hash: 8d8d5fe6dedeb8480fa02f422469754a8895f666

```
/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17
        throw new Error_1.default.InvalidParameter("You must pass in a Model or model name as a string.");
        ^

InvalidParameter: You must pass in a Model or model name as a string.
    at returnObject (/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17:15)
    at Object.<anonymous> (/home/andrewda/Development/dynamoose/playground.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by andrewda** [comment]
@dynamoose/bot stacktrace-parser
Commit Hash: 8d8d5fe6dedeb8480fa02f422469754a8895f666

```
/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17
        throw new Error_1.default.InvalidParameter("You must pass in a Model or model name as a string.");
        ^

InvalidParameter: You must pass in a Model or model name as a string.
    at returnObject (/home/andrewda/Development/dynamoose/packages/dynamoose/dist/ModelStore.js:17:15)
    at Object.<anonymous> (/home/andrewda/Development/dynamoose/playground.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```
